# Generated by Django 2.1.5 on 2023-02-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_pageadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageAdmin',
        ),
    ]
