# Generated by Django 2.1.5 on 2023-02-02 01:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_delete_pageadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 2, 2, 1, 31, 38, 772830, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
